spring:
    application:
        name: book_exchange

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:bookexchange_db}
        username: ${DB_USER:bookexchange_user}
        password: ${DB_PASSWORD:bookexchange_pass}

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

    thymeleaf:
        cache: false

server:
    port: ${SERVER_PORT:9090}

logging:
    level:
        org.hibernate.SQL: info

app:
    admin:
        full-name: ${ADMIN_FULL_NAME:System Administrator}
        email: ${ADMIN_EMAIL:admin@bookexchange.local}
        password: ${ADMIN_PASSWORD:Admin@12345}
